# Application Configuration
quarkus.application.name=ems-backend
quarkus.http.port=8080

# Datasource - PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ems
quarkus.datasource.username=ems
quarkus.datasource.password=ems

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.sql-load-script=no-file

# Validation
quarkus.hibernate-validator.fail-fast=true


# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.clean-at-start=false
quarkus.liquibase.validate-on-migrate=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# Security & JWT
mp.jwt.verify.issuer=https://ems.com
quarkus.smallrye-jwt.auth-mechanism=MP-JWT
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.verify.key.location=publicKey.pem

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, PUT, POST, DELETE, OPTIONS, PATCH

# Mailer (MailHog)
quarkus.mailer.from=no-reply@ems.com
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.mock=false

# Quinoa (Frontend Bundling)
quarkus.quinoa.ui-dir=../frontend
quarkus.quinoa.package-manager-install=npm install
quarkus.quinoa.package-manager-build=npm run build
quarkus.quinoa.enable-ssr=false
# Since we are using React Router with history mode, we need to redirect 404s to index.html
quarkus.http.root-path=/
quarkus.quinoa.ignored-path-prefixes=/api,/q
