# Production Profile

quarkus.hibernate-orm.log.sql=false
quarkus.log.console.level=INFO

# Mailer (Production - Real SMTP)
# These will be typically provided via environment variables on Render
quarkus.mailer.host=${QUARKUS_MAILER_HOST:smtp-relay.brevo.com}
quarkus.mailer.port=${QUARKUS_MAILER_PORT:465}
quarkus.mailer.username=${QUARKUS_MAILER_USERNAME:none}
quarkus.mailer.password=${QUARKUS_MAILER_PASSWORD:none}
quarkus.mailer.ssl=${QUARKUS_MAILER_SSL:true}
quarkus.mailer.starttls=${QUARKUS_MAILER_STARTTLS:REQUIRED}
quarkus.mailer.mock=${QUARKUS_MAILER_MOCK:false}
# Optional: Only use if seeing certificate issues
# quarkus.mailer.trust-all=${QUARKUS_MAILER_TRUST_ALL:false}


ems.google.enabled=true
