# Development Profile
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
quarkus.log.console.level=INFO

# Mailer (Development - MailHog)
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.mock=false

ems.google.enabled=true
ems.google.client-id=1059488907995-70vtm95ee0caicac8fjdic03t4klrfcc.apps.googleusercontent.com